config/routes.rb
Rails.application.routes.draw do
 
  root "billboards#index"
  resources :artists do
    resources :songs
end

  resources :billboards do
    resources :songs
  
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  
end

app/models/billboard.rb
class Billboard < ApplicationRecord
has_many :songs, dependent: :destroy

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard, optional: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  
  
  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    # /billboards/:billboard_id/artists/new
   @artist = Artist.new
   render partial: "form"
  end
  
  def edit
    render partial: "form"
  end

  def create
    # /billboards/:billboard_id/artists
  @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist)
    else 
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to artist_path(@billboard, @artist)
    else 
      render :edit
    end
  end 

  def destroy
    @artist.destroy
    redirect_to billboard_songs_path
  end


  private 

  def set_artist
    @artist = Artist.find(params[:id])

  end


  def artist_params   
      params.require(:artist).permit(:name)
    end
  end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController

before_action :set_billboard, only: [:show, :edit, :update, :destroy]

def index
  @billboards = Billboard.all
end

def show
end

def new
  @billboard = Billboard.new
  render partial: "form"
end

def edit
  render partial: "form"
end

def create
  @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to @billboard
    else 
      render :new 
  end
end

def update
  if @billboard.update(billboard_params)
    redirect_to @billboard
  else
    render :edit
  end
end 

def destroy
  @billboard.destroy
  redirect_to @billboard
end


private 

def set_billboard
  @billboard = Billboard.find(params[:id])
  end

def billboard_params
  params.require(:billboard).permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
  before_action :set_song, only: [:show, :edit, :update, :destroy] 
  
  
  def index
    @songs = Song.all
  end

  def show
  end

  def edit
    render partial: "form"
  end

  def new
    @song = Song.new 
    render partial: "form"
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_path(@artist)
 
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

end

private

def set_artist
  @artist = Artist.find(params[:artist_id])
end

def set_song
  @song = Song.find(params:[id])
end

def song_params 
  params.require(:artist).permit(:name)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<button class="ui primary basic button">
<%= link_to "Back to Billboards", billboards_path %>
</button>

<html>
  <head>
   <link href="https://fonts.googleapis.com/css?family=Bungee+Shade&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Bungee Shade', cursive;
        font-size: 25px;
      }
      
    </style>
    
  </head>
  <body>
    <div>Artists</div>
     </body>
</html>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
</ul>
<ul>






  

app/views/artists/new.html.erb
<h1>Add An Artist</h1>
<%= form_for [@artist] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<button class="ui primary basic button">
<%= link_to "Back to Artists", artists_path %>
</button>

<html>
  <head>
   <link href="https://fonts.googleapis.com/css?family=Bungee+Shade&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Bungee Shade', cursive;
        font-size: 25px;
      }
      
    </style>
    
  </head>
  <body>
    <div>Songs</div>
     </body>
</html>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? "Edit Billboard" : "New Billboard" %></h1>
<hr />
<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<html>
  <head>
   <link href="https://fonts.googleapis.com/css?family=Bungee+Shade&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Bungee Shade', cursive;
        font-size: 60px;
      }
      
    </style>
    
  </head>
  <body>
    <div>The Billboard</div>
     </body>
</html>
<html>
 <div class="ui basic yellow button">
<%= link_to 'Create a New Billboard', new_billboard_path(@billboards) %>
</div>
<div>
<button class="ui teal basic button">
   <%= link_to "View Artists ", artists_path(@artist) %>
</div>
<ul>
  <% @billboards.each do |billboard| %>
    
    <li><%= link_to "#{billboard.name}", billboard_path(billboard) %></li>
  <% end %>
</ul>




</html>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<button class="ui primary basic button">
<%= link_to "Back to Billboards", billboards_path %>
</button>

<h1><%= @billboard.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to "Add Artists", new_artist_path(@billboard) %>

<br />
<%= link_to "Edit Billboard", edit_billboard_path(@billboard) %>
<br />
<%= button_to "Delete Billboard", artist_path(@billboard), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? "Edit Song" : "New Song" %></h1>
<hr />
<%= form_for @song do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<button class="ui primary basic button">
<%= link_to "Back to Aritsts", artist_path %>
</button>

<html>
  <head>
   <link href="https://fonts.googleapis.com/css?family=Bungee+Shade&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Bungee Shade', cursive;
        font-size: 25px;
      }
      
    </style>
    
  </head>
  <body>
    <div>Songs</div>
     </body>
</html>